# Generated by Django 2.2.16 on 2020-09-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottlefile',
            fields=[
                ('filepath', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('bottlefile_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bottlefile',
            },
        ),
        migrations.CreateModel(
            name='Cabinets',
            fields=[
                ('shortname', models.CharField(max_length=32)),
                ('longname', models.CharField(max_length=128)),
                ('room', models.CharField(max_length=64)),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('cabinet_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cabinets',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('name', models.CharField(max_length=32)),
                ('comments', models.CharField(max_length=132)),
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('firstname', models.CharField(max_length=64)),
                ('lastname', models.CharField(blank=True, max_length=64, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Producers',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('url', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', models.CharField(blank=True, max_length=128, null=True)),
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'producers',
            },
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('short_name', models.CharField(max_length=32)),
                ('long_name', models.CharField(max_length=64)),
                ('si_conversion_factor', models.FloatField()),
                ('unit_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'units',
            },
        ),
        migrations.CreateModel(
            name='Shelves',
            fields=[
                ('shortname', models.CharField(max_length=32)),
                ('longname', models.CharField(blank=True, max_length=128, null=True)),
                ('comments', models.CharField(blank=True, max_length=128, null=True)),
                ('shelf_id', models.AutoField(primary_key=True, serialize=False)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Cabinets')),
            ],
            options={
                'db_table': 'shelves',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('property_name', models.CharField(max_length=32)),
                ('short_name', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=128)),
                ('pictogram_path', models.CharField(max_length=256)),
                ('property_id', models.AutoField(primary_key=True, serialize=False)),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Cabinets')),
            ],
            options={
                'db_table': 'properties',
            },
        ),
        migrations.CreateModel(
            name='Chemicals',
            fields=[
                ('iupac_name', models.CharField(blank=True, max_length=128, null=True)),
                ('trivial_name', models.CharField(max_length=128)),
                ('cas', models.CharField(max_length=32)),
                ('formula', models.CharField(blank=True, max_length=32, null=True)),
                ('chemical_id', models.AutoField(primary_key=True, serialize=False)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Properties')),
            ],
            options={
                'db_table': 'chemicals',
            },
        ),
        migrations.CreateModel(
            name='Bottles',
            fields=[
                ('product_name', models.CharField(blank=True, max_length=128, null=True)),
                ('quality', models.CharField(blank=True, max_length=32, null=True)),
                ('amount', models.FloatField()),
                ('registered_date', models.DateField()),
                ('barcode', models.CharField(max_length=128, unique=True)),
                ('comments', models.CharField(blank=True, max_length=256, null=True)),
                ('bottle_id', models.AutoField(primary_key=True, serialize=False)),
                ('producer_id', models.PositiveIntegerField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Chemicals')),
                ('loaner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loaner', to='blog.Persons')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_person', to='blog.Persons')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.Shelves')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.Units')),
            ],
            options={
                'db_table': 'bottles',
            },
        ),
    ]
