# Generated by Django 3.1.1 on 2020-09-29 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottlefile',
            options={'verbose_name': 'bottlefile', 'verbose_name_plural': 'bottlefiles'},
        ),
        migrations.AlterModelOptions(
            name='bottles',
            options={'verbose_name': 'bottle', 'verbose_name_plural': 'bottles'},
        ),
        migrations.AlterModelOptions(
            name='cabinets',
            options={'verbose_name': 'cabinet', 'verbose_name_plural': 'cabinets'},
        ),
        migrations.AlterModelOptions(
            name='chemicals',
            options={'verbose_name': 'chemical', 'verbose_name_plural': 'chemicals'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'location', 'verbose_name_plural': 'locations'},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
        migrations.AlterModelOptions(
            name='producers',
            options={'verbose_name': 'producer', 'verbose_name_plural': 'producers'},
        ),
        migrations.AlterModelOptions(
            name='properties',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='shelves',
            options={'verbose_name': 'shelf', 'verbose_name_plural': 'shelves'},
        ),
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'unit', 'verbose_name_plural': 'units'},
        ),
        migrations.RemoveField(
            model_name='bottles',
            name='producer_id',
        ),
        migrations.AddField(
            model_name='bottles',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='blog.producers'),
        ),
    ]
