# Generated by Django 3.1.1 on 2020-10-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200929_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUpdate',
            fields=[
                ('entry_id', models.AutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('entry_content', models.TextField()),
                ('entry_author', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Storage update',
                'verbose_name_plural': 'Storage updates',
                'db_table': 'Storage Update',
            },
        ),
    ]
